-- Rescues and Locations Audit - MIGRATION CONSOLIDATED
-- 
-- NOTE: This migration has been consolidated into migration 2025122802
-- All audit tables, triggers, functions, and views for rescues and locations
-- are now created in 2025122802_dogadopt_rescues_and_locations.sql BEFORE
-- the data is inserted, ensuring that INSERT operations are properly audited.
--
-- This file is kept for migration history tracking but contains no operations.
-- The audit system is fully functional and captures all changes including
-- initial data inserts.
--
-- For details on the audit system, see:
-- - /workspaces/adopt-a-dog-uk/docs/RESCUES_LOCATIONS_AUDIT.md
-- - /workspaces/adopt-a-dog-uk/supabase/migrations/2025122802_dogadopt_rescues_and_locations.sql

-- No operations needed - all audit functionality moved to 2025122802
